# Borrowed by https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development
# and https://github.com/evilmartians/terraforming-rails/blob/master/examples/devcontainer/docker-compose.yml
version: "3.4"

volumes:
  bundle:
  node_modules:
  rails_cache:
  home:
  # redis:
  packs:
  postgres:

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
    args:
      RUBY_VERSION: "2.4.6"
      PG_MAJOR: "9.6"
      NODE_MAJOR: "10"
      YARN_VERSION: "1.13.0"
      BUNDLER_VERSION: "1.17.3"
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
  image: example-dev:1.1.0
  tmpfs:
    - /tmp
  volumes:
    - home:/root

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - ..:/app
    # - rails_cache:/app/tmp/cache
    # - bundle:/usr/local/bundle
    # - node_modules:/app/node_modules
    # - packs:/app/public/packs
    - ./.psqlrc:/root/.psqlrc:ro
    # - ./.bashrc:/root/.bashrc:ro
    - home:/root
    - $HOME/.ssh/:/home/vscode/.ssh:ro # Mount the ssh folder
  environment:
    <<: *env
    WEBPACKER_DEV_SERVER_HOST: webpacker
    WEB_CONCURRENCY: 1
    APP_MAX_PROCESS: 2
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: vi
  # depends_on:
  #   postgres:
  #     condition: service_healthy
  #   redis:
  #     condition: service_healthy

services:
  editor:
    <<: *backend
    command: /bin/bash
    network_mode: host
